fix

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,43 +8,55 @@ log() {
 
 log "Start!!!"
 
+DOTFILES_REPO="https://github.com/taakuuyaa/dotfiles.git"
 DOTFILES_PATH="$HOME/dotfiles"
 
-# Git clone dotfiles
-if [ ! -d "$DOTFILES_PATH" ]; then
-  log "Cloning dotfiles repository..."
-  git clone --recursive https://github.com/taakuuyaa/dotfiles.git "$DOTFILES_PATH"
-else
-  log "Dotfiles repository already exists. Skipping clone."
-fi
+clone_dotfiles() {
+  if [ ! -d "$DOTFILES_PATH" ]; then
+    log "Cloning dotfiles repository..."
+    git clone --recursive "$DOTFILES_REPO" "$DOTFILES_PATH"
+  else
+    log "Dotfiles repository already exists. Skipping clone."
+  fi
+}
 
-# Setup Homebrew
-if ! command -v brew >/dev/null 2>&1; then
-  log "Installing Homebrew..."
-  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-else
-  log "Homebrew is already installed."
-fi
+install_homebrew() {
+  if ! command -v brew >/dev/null 2>&1; then
+    log "Installing Homebrew..."
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+  else
+    log "Homebrew is already installed."
+  fi
+}
 
-# Update and check Homebrew
-log "Running brew doctor and brew update..."
-brew doctor
-brew update
+update_homebrew() {
+  log "Running brew doctor and brew update..."
+  brew doctor || log "brew doctor encountered an error, but continuing..."
+  brew update || log "brew update encountered an error, but continuing..."
+}
 
-# Install Homebrew Bundle
-if [ -f "$DOTFILES_PATH/Brewfile" ]; then
-  log "Installing packages from Brewfile..."
-  brew bundle --file="$DOTFILES_PATH/Brewfile"
-else
-  log "Brewfile not found at $DOTFILES_PATH. Skipping Homebrew Bundle."
-fi
+install_brew_bundle() {
+  if [ -f "$DOTFILES_PATH/Brewfile" ]; then
+    log "Installing packages from Brewfile..."
+    brew bundle --file="$DOTFILES_PATH/Brewfile" -v
+  else
+    log "Brewfile not found at $DOTFILES_PATH. Skipping Homebrew Bundle."
+  fi
+}
 
-# Link dotfiles using rcm
-if command -v rcup >/dev/null 2>&1; then
-  log "Linking dotfiles with rcm..."
-  env RCRC="$DOTFILES_PATH/rcrc" rcup
-else
-  log "rcm is not installed. Please install it to link dotfiles."
-fi
+link_dotfiles() {
+  if command -v rcup >/dev/null 2>&1; then
+    log "Linking dotfiles with rcm..."
+    env RCRC="$DOTFILES_PATH/rcrc" rcup
+  else
+    log "rcm is not installed. Please install it to link dotfiles."
+  fi
+}
+
+clone_dotfiles
+install_homebrew
+update_homebrew
+install_brew_bundle
+link_dotfiles
 
 log "End!!!"
